### ISSUE TITLE
kinto init should generate a configuration file with kinto-changes and kinto-attachment configuration

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto-dist#1]

**Comment by leplatrem** [comment]
Each plugin could have a callback to insert some default configuration when installed :)

**Comment by leplatrem** [comment]
Move issue to kinto repo ?

**Comment by Natim** [comment]
Yes let's move it to kinto.

**Comment by Natim** [comment]
See https://github.com/Kinto/kinto/issues/721
