### ISSUE TITLE
AMO blocklists.json file doesn't exists anymore

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto-dist#111]
We should change the functional test to make it works without relying on json2kinto.

**Comment by Natim** [comment]
https://gist.githubusercontent.com/jasonthomas/ac0d17bd9082b9ee7604ad3fe0773a74/raw/ea98eacf5518e44485312e3488edce4444af995f/blocklists.json

**Comment by leplatrem** [comment]
Done
