### ISSUE TITLE
kinto-dist logging is duplicating messages

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto-dist#113]
Is this a logger issue?

**Comment by jasonthomas** [comment]
https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/kintowe/puppet/modules/kintowe/templates/kinto.ini.erb#L104 is what we have configured in kinto web extensions stack.

**Comment by jasonthomas** [comment]
This is no longer a issue.
