### ISSUE TITLE
Integration tests cannot connect to postgresql on circleci

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto-dist#1168]
https://circleci.com/gh/mozilla-services/kinto-dist/4724

**Comment by glasserc** [comment]
I guess this has been happening more and more frequently. Maybe we need to put a check to wait until PostgreSQL comes up, or maybe the version of the postgresql container has some kind of problem?

**Comment by Natim** [comment]
We could use something like that:

```
until PGPASSWORD=$DATABASE_PASSWORD psql -h $DATABASE_HOST -U $DATABASE_USER -d $DATABASE_NAME -c  '\q'; do
  >&2 echo "Postgres is unavailable - sleeping 🙀"
  sleep 1
done

>&2 echo "Postgres is up - executing command ✅"
```
