### ISSUE TITLE
Why does smoke-test.sh pull a fixed version of e2e.py from kinto-signer?

### ISSUE THREAD

**Issue by glasserc** [mozilla-services/kinto-dist#117]
smoke-test.sh contains the following code:

```sh
curl -O https://raw.githubusercontent.com/Kinto/kinto-signer/1.3.0/scripts/e2e.py
```

Note that the version of `e2e.py` is taken from `kinto-signer` 1.3.0. However, later in the file is:

```sh
curl -O https://raw.githubusercontent.com/Kinto/kinto-signer/master/scripts/validate_signature.py
```

My questions are:

1. Why 1.3.0 instead of master? Is this meant to be a "known good" version? Is it supposed to represent existing code "in the wild"?
2. For that matter, why master instead of some "latest release"?
3. Actually, why do we `curl` these files at all rather than i.e. extracting them from installed packages?

**Comment by Natim** [comment]
To be honest I don't recall why we are doing it like that. I guess that's because we don't ship the scripts with the release

**Comment by leplatrem** [comment]
* 1 - known good version, probably becuase of some breaking changes at some point
* 2 - latest release would be better yes
* 3 - those scripts are not packaged with the python code

**Comment by glasserc** [comment]
We no longer using `master` in `smoke-test.sh`, but another "known good" version. That's good enough for my purposes.
