### ISSUE TITLE
Add integration test for review workflow + attachments

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto-dist#147]

**Comment by peterbe** [comment]
Does the smoke-test.sh not have this?

**Comment by leplatrem** [comment]
Nope, current the smoke-test has just one test: it creates a record with an attachment.

The goal of this issue is to implement a test that will:
- create a record with an attachment
- request a review and approve it
- attach another file to the same record
- request a review and approve it

**Comment by jrbenny35** [comment]
This should be fixed in #1083 !
