### ISSUE TITLE
Enable Renovate

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto-dist#202]

**Comment by peterbe** [comment]
Or, we can just add Renovate which can do our package.json AND our requirements.txt
https://twitter.com/renovatebot/status/1014788424048443392

**Comment by leplatrem** [comment]
Yes!

**Comment by peterbe** [comment]
Let's do this as soon as https://github.com/mozilla-services/kinto-dist/pull/214 lands. Oh how I miss Bugzilla's dependency tracker sometimes. 

Note-to-self; the place to go to get started is: https://mana.mozilla.org/wiki/display/SVCOPS/Application+Dependency+Management

**Comment by peterbe** [comment]
I see that Renovate *is* enabled now.
