### ISSUE TITLE
Which kinto-dist release is affected by the security fix in kinto 8.3.0?

### ISSUE THREAD

**Issue by jayfk** [mozilla-services/kinto-dist#215]
Kinto 8.3.0 has a security fix: https://github.com/Kinto/kinto/blob/master/CHANGELOG.rst#830-2018-04-06

Which kinto-dist release is affected by this so that we can update Safety DB/pyup.io accordingly?

cc @Jwomers

**Comment by leplatrem** [comment]
According to version range mentioned in the Kinto CHANGELOG and the kinto-dist CHANGELOG: 
- 6.0.0
- 6.0.1
- 6.0.2
