### ISSUE TITLE
Download kinto-admin config file from URL in settings

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto-dist#22]
We should not bind this repository to amo. 
I suggest that when kinto-dist starts we look at a URL in settings and download the json config from it if missing locally. What do you think?

**Comment by Natim** [comment]
I think we need to define the workflow to provide a kinto-admin dashboard.
The more I think about it the more I am convinced that we should not deploy the dashboard with kinto-dist but we should have different admin deploy for each use-case (One for Fennec, One for AMO, etc)

**Comment by Natim** [comment]
So to answer your issue, the solution might be to remove kinto-admin from kinto-dist alltogether.

**Comment by leplatrem** [comment]
Closing now that next kinto-admin version does not require any input file.
