### ISSUE TITLE
Possible blocklists CloudFront cache invalidation issue

### ISSUE THREAD

**Issue by autrilla** [mozilla-services/kinto-dist#230]
On 2018-07-16T18:37:00Z I got notified that @wagnerand could not see the block with id ae8ae617-590d-430b-86d4-16364372b67f on the endpoint https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%7Bx%7D/1.0/. A few minutes later, it was confirmed that the record could be seen, and that this was a cache issue. I checked the AWS CloudFront control panel and saw nothing at all under "Invalidations". Are the blocklists endpoints invalidated at all? According to @wagnerand it took 30-40 minutes for the block to be available. Some delay is expected even when invalidating, but 30-40 minutes seems excessive to me.

**Comment by mostlygeek** [comment]
Looks like there is only an ELB in front of blocklists.settings.s.m.c.   @leplatrem is the XML generated dynamically from the data in kinto?

**Comment by autrilla** [comment]
Yeah, I think you're right. I think nginx does proxy cloudfront. It proxies traffic to "firefox.settings.services.mozilla.com" (https://github.com/mozilla-services/cloudops-deployment/blob/dfcc0a09c824f05ea53e1deb136f4dc392b11d7d/projects/kintoblocklist/puppet/modules/blocklist/templates/nginx.conf.erb#L30) which points to cloudfront. Nginx then adds caching in front of it and isn't aware of the invalidations. Is the hour-long worst case delay acceptable (cc @wagnerand)? If not, I can look into the ways we can improve upon it.

The cloudfront distribution I was looking at previously (E1LXMF6YV37TQT, named "Kinto Blocklist Blocked CDN") seems to be unrelated, and I don't see it generating any logs recently, so it's probably unused. So it being unused is probably the reason there's no invalidations there.

**Comment by wagnerand** [comment]
I believe this is ok for now, but it's good for us admins to know about this. We might want to revisit later to see if we can shorten the delay, but it shouldn't be a problem right now. Thank you.

**Comment by leplatrem** [comment]
The sad part is that we are about to have live updates for Remote Settings, but the blocklist code still relies on this old XML tech (See [Bug 1257565](https://bugzilla.mozilla.org/show_bug.cgi?id=1257565))

**Comment by mostlygeek** [comment]
We're going to be reducing the TTL from 60m to 30m in:  https://github.com/mozilla-services/cloudops-deployment/pull/2286
