### ISSUE TITLE
don't digest pin services in docker-compose

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/kinto-dist#253]
See https://github.com/mozilla-services/tecken/pull/1019

At the time of writing, I haven't been able to confirm that it works but @rarkins [says it looks right](https://github.com/renovatebot/renovate/issues/2415#issuecomment-415481282).

**Comment by rarkins** [comment]
Renovate will only add digests in Docker managers if pinDigests=true. By default it’s false and I don’t see anywhere where it would get switched on by accident. 

Setting docker-compose.digest.enabled=false in config is kind of a safety measure that should stop Renovate ever *updating* digests for Docker Compose specifically.

**Comment by peterbe** [comment]
Oh. Now I'm confused. 

For starters, the only reason we have [a digest on the `Dockerfile`](https://github.com/mozilla-services/kinto-dist/blob/32a1c99d241a80d5f450a5474cc23a825de978ef/Dockerfile#L1) is that I put that there manually (copied from another project). 

So how do I edit the `renovate.json` to do digest pinning on `Dockerfile` files but *not* on `docker-compose.yml`?

**Comment by peterbe** [comment]
Note-to-self; I need to learn from this (last comment question), into [mozilla/tecken](https://github.com/mozilla-services/tecken/blob/master/renovate.json) too.

**Comment by rarkins** [comment]
> So how do I edit the renovate.json to do digest pinning on Dockerfile files but not on docker-compose.yml?

You could add this:

```json
  "dockerfile": {
    "pinDigests": true
  }
```

**Comment by peterbe** [comment]
Like [this](https://github.com/mozilla-services/tecken/pull/1021)?

**Comment by rarkins** [comment]
yes
