### ISSUE TITLE
How can I easily upgrade kinto-dist on my server?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto-dist#270]
Before the huge refactoring of requirements, I could do this on my server:

```
pip install -U kinto-dist==9.1.4
```

And it would install every dependency at their new version within the required version range.

Now, since the kinto-dist package has no `install_requires` in `setup.py`, the pip install does nothing basically. Which makes me wonder if we should still have a package in this case BTW.

To upgrade the server, I did this basically:

```
$ curl https://raw.githubusercontent.com/mozilla-services/kinto-dist/master/requirements/constraints.txt > /tmp/constraints.txt
$ pip install -r /tmp/constraints.txt
```

@peterbe is that a common way to do it? What would you suggest me to do instead?

**Comment by peterbe** [comment]
To upgrade your own server you just do what Dockerfile does which is:

```
git pull origin master
pip install -r requirements/default.txt -c requirements/constraints.txt
```

That'll get you the exact same versions of everything as we use in Docker in Cloud OPs EC2. 

Another option that might be smart is to always start afresh. Eg.

```
git pull origin master
rm -fr .venv
virtualenv -p /path/to/preffered/python .venv
source .venv/bin/activate
pip install -r requirements/default.txt -c requirements/constraints.txt
```

That way, in case your old env had some junk installed that we longer use you won't get that any more. 

Did I understand the question correctly?

**Comment by leplatrem** [comment]
Yes thanks, so you are telling me to clone the repo basically.

With the current approach, it makes no sense to publish a package on pypi. 

So, we can just delete the setup.py, or alternatively restore the list of requirements in setup.py.

**Comment by peterbe** [comment]
Well, if you ever want to depend on `kinto-dist` from another package the `setup.py` is the only way. You get best of both worlds by doing something like:

```python
setup(
    ...
    install_requires=[x.split('==')[0] for in read('./requirements/default.txt') if not x.startwith(' ')]
```

Right? But is it ever applicable?

Docker deployments are kinda like a fresh `git clone` every time. I guess if you want it on your own server it's technically called `git pull`. :)

**Comment by leplatrem** [comment]
> Right? But is it ever applicable?

Without version range it makes little sense

**Comment by peterbe** [comment]
> With the current approach, it makes no sense to publish a package on pypi.

Well, kinto-dist shouldn't be on PyPI but kinto probably should. 

> So, we can just delete the setup.py, or alternatively restore the list of requirements in setup.py.

Yes, I say we delete the setup.py in kinto-dist.

**Comment by leplatrem** [comment]
> Well, kinto-dist shouldn't be on PyPI but kinto probably should.

I understand your position, but I don't necessarily agree with this. kinto-dist is a meta-package, and installing it with pip still makes sense IMO

> Yes, I say we delete the setup.py in kinto-dist.

With the current state of the repo it doesn't make sense to keep it :) 

I will think more about this and decide ;)
