### ISSUE TITLE
Don't upgrade services versions

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/kinto-dist#499]
We've already instructed Renovate to [*not* bother with digests on docker-compose](https://github.com/mozilla-services/kinto-dist/blob/0172e4ecedf2ea440445b4d029fcdf24fe0923e3/renovate.json#L5) ([PR](https://github.com/mozilla-services/kinto-dist/issues/253))
But it's not stopping them from upgrading the versions of things. [E.g. this](https://github.com/mozilla-services/kinto-dist/commit/2828630c38c15c249dc6e673dcc51f0edece4528#diff-4e5e90c6228fd48698d074241c2ba760)

Can we instruct Renovate to not bother touching these?

The only thing that matters is that we use the (exact) same version of services in `docker-compose` as the versions we get of things in production. (The assumption is that for `kinto-dist` there is only *one* production instance). If we use Postgres 9.6.42 in production we should have 9.6.42 in `docker-compose` and not let Renovate suggest upgrades to that.

**Comment by leplatrem** [comment]
@bqbn How could we continuously know which versions we are running in production? 
What's your advice on this? Should run our integration tests here with the latest versions?

Mainly:
- autograph
- postgres
- megaphone
- mysql
- memcached

**Comment by bqbn** [comment]
> * autograph
> * megaphone

All cloudops managed services like the above two should have a `/__version__` endpoint, that's how we know their versions. If an app doesn't have that endpoint, then it's a bug, and we should file a bug with that app and have it fixed.

> * postgres
> * mysql
> * memcached

For these software, if we really want to **continuously** know its version, then the kinto app needs to query them directly and expose an endpoint to return the value. Take postgres for example, the app can query `SELECT version();` to get its version.

That said, I don't know what the value we gain from **continuously** knowing the version of the database and the memcached, nor do I know if it's worth the effort doing it, versus, for example, just asking ops what versions are in -prod (when/if in doubt).

**Comment by leplatrem** [comment]
> That said, I don't know what the value we gain from continuously knowing the version of the database and the memcached

Well, the goal is mostly about running integration tests using the exact same version as what's in prod, which is likely to evolve over time.

I wouldn't mind running everything with the latest version actually. It helps find out issues early
