### ISSUE TITLE
uwsgi segfault, maybe we can tweak the conf to make uwsgi less greedy for travis.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto-dist#50]

**Comment by Natim** [comment]
You will need to revert https://github.com/mozilla-services/kinto-dist/pull/49/commits/9fd708350a9fa98ab55cdfb7e1cd721cad4ae597 in order to do that.

**Comment by leplatrem** [comment]
@Natim is this still a thing?

**Comment by Natim** [comment]
I haven't tried, I am not worried about using pserve instead of uwsgi so maybe we can just close this.

**Comment by peterbe** [comment]
Is this issue only about CI? I.e. uwsgi segfaults only in Travis CI?

**Comment by leplatrem** [comment]
I think we can close this
