### ISSUE TITLE
Renovate should not touch our autograph version

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/kinto-dist#500]
In a similar vein as https://github.com/mozilla-services/kinto-dist/issues/499
The most important thing is that our CI uses the same version of autograph that gets used in production. We shouldn't let Renovate suggest upgrades to the version. Sure, they can suggest new digests but it shouldn't change the version number. 
E.g. This is not right: https://github.com/mozilla-services/kinto-dist/commit/35faacdfa9595b4d327c03bf9deaa1f5facc6507#diff-328809e9ee1fd7c69625861bc4bd64da

**Comment by leplatrem** [comment]
Autograph now gets deployed continuously, so we should run its latest version in our tests.
